project:
  type: website
  output-dir: "docs"

website:
  title: "Statistics Labs Hub"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Beyond MLR"
        menu:
          - text: "Lab 1"
            href: Beyond_MLR/BLR_lab1.qmd
          - text: "Lab 2"
            href: Beyond_MLR/BLR_lab2.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
