project:
  type: website

website:
  title: "My Courses"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Beyond MLR"
        menu:
          - text: "Lab 1"
            href: Beyond MLR/BLR_lab1.qmd
          - text: "Lab 2"
            href: Beyond MLR/BLR_lab2.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
